In [ ]:
print("HEllo 101")
print("LAB-1")

HEllo 101
LAB-1


LAB-1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.array([[1,2,3.2],[4,2,5]])

In [ ]:
arr

array([[1. , 2. , 3.2],
       [4. , 2. , 5. ]])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(np.ndim(arr))

2


In [ ]:
print(np.shape(arr))

(2, 3)


In [ ]:
print(np.size(arr))

6


In [ ]:
print(arr.dtype)

float64


In [ ]:
list=[1,2,3]
tuple=(1,0,1)
dict={1:1,2:0,3:1}
ar=np.array(list)
ar1=np.array(tuple)
ar2=np.array(dict)
print(ar)
print(ar1)
print(ar2)

[1 2 3]
[1 0 1]
{1: 1, 2: 0, 3: 1}


In [ ]:
z=np.zeros([3,4])
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
f=np.full((3,4),7,dtype='complex')
f

array([[7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j]])

In [ ]:
print(np.random.random((2,2)))


[[0.4175142  0.52277283]
 [0.90808558 0.56652087]]


In [ ]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [ ]:
print(np.linspace(0,5,3))

[0.  2.5 5. ]


In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],
                [1, 2, 0, 1]])

In [ ]:
np.shape(arr)

(3, 4)

In [ ]:
arr.reshape(2,3,2)

array([[[1, 2],
        [3, 4],
        [5, 2]],

       [[4, 2],
        [1, 2],
        [0, 1]]])

In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1])

In [ ]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 

In [ ]:
arr[1:3:4]

array([[ 4. , -0.5,  6. ,  0. ]])

In [ ]:
arr[:2,::2]

array([[-1.,  0.],
       [ 4.,  6.]])

In [ ]:
  arr[1:3,::]

array([[ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ]])

In [ ]:
cond=arr>2
temp=arr[cond]
temp

array([4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. ])

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
a.T

array([[1, 3, 9],
       [2, 4, 6],
       [3, 5, 0]])

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print(a.max(axis=0))
print(a.max(axis=1))

[9 6 5]
[3 5 9]


In [ ]:
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 3,  7, 12],
       [ 9, 15, 15]])

In [ ]:
#LAB-2

LAB-2

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
#print(a,b)
print(np.vstack((c,b,a)))
print("    ")
print(np.hstack((a,c)))
print("    ")
print(np.concatenate((a,b,c)))

[[ 9 10]
 [11 12]
 [ 5  6]
 [ 7  8]
 [ 1  2]
 [ 3  4]]
    
[[ 1  2  9 10]
 [ 3  4 11 12]]
    
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
try:  #splitting
  a=np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
  print(np.vsplit(a,2))
except ValueError:
  print("Value error")


[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [ ]:
a=np.array([1,2,3])
b=2
c=[2,2,2]
print(a*b)
print(a*c)

[2 4 6]
[2 4 6]


In [ ]:
#Pandas
import pandas as pd

In [ ]:
data=np.array(['russel','surya','abd','ambati'])


0    russel
1     surya
2       abd
3    ambati
dtype: object


In [ ]:
ser=pd.Series(data)
print(ser)


0    russel
1     surya
2       abd
3    ambati
dtype: object


In [ ]:
ser=pd.Series(data,index=[10,20,30,40])
print(ser)

10    russel
20     surya
30       abd
40    ambati
dtype: object


In [ ]:
dict={1:'a',2:'b',3:'c'}
ser=pd.Series(dict)
print(ser)


1    a
2    b
3    c
dtype: object


In [ ]:
ser=pd.Series(10,index=[0,1,2,3,4,5])
print(ser)

0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64


In [ ]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
df=pd.read_csv('sample_data/mnist_test.csv')
df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]